### ISSUE TITLE
[Bug] Empty backups created/erasing old backups

### ISSUE THREAD

**Issue by FelesNoctis** [Forevener/AutoBackuper#1] opened 2020-06-05 22:50 UTC
During my initial tests, I noticed that AutoBackuper seems to be creating empty zips. I believe these are files that are re-dated when the watched program is closed, but the content of the files is identical
_Example: 1st & 5th slots_
_https://i.imgur.com/M0NsdEc.png_

When reaching the maximum number of slots available for that file's backup (in this case **5**), this results in erasing an older backup that actually contained viable content.
_Example: 1st (6th backup) & 5th slots_
_https://i.imgur.com/ZDhjUjc.png_

Every backup after this continued to create empty zips despite file contents changing.

**Comment by Forevener** [comment] 2020-06-06 08:33
Very interesting, it should not ever create empty archives - since application watches every change for every file/directory and tries to archive exactly them.
1. Could you also take a look at the log? Perhaps we could find something useful there, like warnings or errors related to file availability.
2. Watcher fires its events when file changes in any possible way, so that's intended behaviour. I could implement checksum comparison to prevent backuping files with no real changes, but that will decrease the performance...
3. Rewriting last slot is intended behaviour, so backups are cycling all the time. What I haven't implemented though is unlimited slots, so I should probably get to that.

**Comment by FelesNoctis** [comment] 2020-06-09 00:05
Sorry about the delay! Can't remember the last time I've been that busy on a weekend.

> 2020-06-08 4:57:49 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed
2020-06-08 4:57:49 PM Successfully saved to C:\Users\bwfan\Downloads\_Github Testing\Autobackuper\Backups\Mids Reborn\Config.json-AS_B2.zip
2020-06-08 4:57:49 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed
2020-06-08 4:57:49 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.json - Changed
2020-06-08 4:57:49 PM Successfully saved to C:\Users\bwfan\Downloads\_Github Testing\Autobackuper\Backups\Mids Reborn\Compare.json-AS_B2.zip
2020-06-08 4:57:49 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.json - Changed
2020-06-08 4:57:49 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.mhd - Changed
2020-06-08 4:57:49 PM Successfully saved to C:\Users\bwfan\Downloads\_Github Testing\Autobackuper\Backups\Mids Reborn\Compare.mhd-AS_B2.zip
2020-06-08 4:57:49 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.mhd - Changed
2020-06-08 4:58:09 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed
2020-06-08 4:58:09 PM ERROR: The process cannot access the file 'C:\Games\City of Heroes\Mids Reborn\Data\Config.json' because it is being used by another process.
2020-06-08 4:58:09 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed
2020-06-08 4:58:09 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.json - Changed
2020-06-08 4:58:09 PM Successfully saved to C:\Users\bwfan\Downloads\_Github Testing\Autobackuper\Backups\Mids Reborn\Compare.json-AS_B3.zip
2020-06-08 4:58:09 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.json - Changed
2020-06-08 4:58:09 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.mhd - Changed
2020-06-08 4:58:09 PM Successfully saved to C:\Users\bwfan\Downloads\_Github Testing\Autobackuper\Backups\Mids Reborn\Compare.mhd-AS_B3.zip
2020-06-08 4:58:09 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.mhd - Changed
2020-06-08 4:58:38 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed
2020-06-08 4:58:38 PM ERROR: The process cannot access the file 'C:\Games\City of Heroes\Mids Reborn\Data\Config.json' because it is being used by another process.
2020-06-08 4:58:38 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed
2020-06-08 4:58:38 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.json - Changed
2020-06-08 4:58:38 PM Successfully saved to C:\Users\bwfan\Downloads\_Github Testing\Autobackuper\Backups\Mids Reborn\Compare.json-AS_B4.zip
2020-06-08 4:58:38 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.json - Changed
2020-06-08 4:58:38 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.mhd - Changed
2020-06-08 4:58:38 PM Successfully saved to C:\Users\bwfan\Downloads\_Github Testing\Autobackuper\Backups\Mids Reborn\Compare.mhd-AS_B4.zip
2020-06-08 4:58:38 PM C:\Games\City of Heroes\Mids Reborn\Data\Compare.mhd - Changed

1. What's interesting about this is that, after retrying it several times, the "cannot access the file" error involving the config file only happens **_after the first backup after launching_**. If I close AutoBackuper and run it again, it'll be able to make a single effective backup of that `config.json` before being unable to access the file again. The source program is able to continue making its changes to the file regardless of AutoBackuper's situation.
2. I was actually considering suggesting checksum when I first made the report. In terms of performance, any attempt to make in-the-moment backups of files that are changing is probably going to have a hit of some kind, right?
3. I know, more commenting on it erasing a legitimate backup with something that's empty. In this case it defeated the purpose of a backup. 😛 If the program's intended effect was only to make backups on an actual change, and it was making empty ones that erased backups with content, that'd be a major issue.

**Comment by Forevener** [comment] 2020-06-09 05:58
Pushed some commits, please rebuild.
1. I wonder if source program doesn't 'release' the file stream. Let's investigate that on the newer version.
2. I'm really uncertain about that - for larger files, checksum calculation could take actual seconds (or even minutes), and if user felt like exactly that version should've been saved (which is not available anymore since it was replaced while we were calculating checksum), he will experience major disappointment.
3. The update contains following change - archive goes into the temporary directory first, and if the archiving process was successful, it will move to backup folder - thus preventing broken backups replacing valid ones.

**Comment by FelesNoctis** [comment] 2020-06-10 20:54
Alright, round two with the new version!
1. Might be, but the source program only saves the config.json on closing. Plus that still doesn't explain why AutoBackuper has no issue with the first attempt, but then complains on subsequent attempts, and if AutoBackuper is restarted it once again doesn't have an issue on the first attempt but complains for each afterwards.
2. True. To make it more robust the backup process would end up extra complicated regardless, maybe more than is really necessary.
3. Looks like that's working! AutoBackuper is still complaining about the file being used by another process, but it's backing up the new version of the file regardless. No broken backups here!

**Comment by Forevener** [comment] 2020-06-11 07:12
1. Well, that's an interesting issue. I managed to reproduce (probably) this bug by rapidly saving 15KB file in Notepad, and it seemed that bug was caused by 'file changed' event firing before change was fully committed (for some reason).
2. Great, it's set then - no checksum! Actually I don't mind to implement something similar, but only if it will take a few milliseconds (or even less) to calculate.
3. Good! Now try the new version please, I've introduced check-and-retry for lock on the file.

_Edit:_ Please take a look at the log during testing - I wonder if AutoBackuper itself locks the file, while trying to create two backups simultaneously.

**Comment by FelesNoctis** [comment] 2020-06-12 23:04
```
2020-06-12 3:52:02 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed
2020-06-12 3:52:02 PM Successfully saved to C:\Users\bwfan\Downloads\_Github Testing\Autobackuper\Backups\Mids Reborn\Config.json-AB_B1.zip
2020-06-12 3:52:02 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed

2020-06-12 3:52:23 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed
2020-06-12 3:52:23 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json is locked, retrying
2020-06-12 3:52:23 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json is locked, retrying
2020-06-12 3:52:23 PM Successfully saved to C:\Users\bwfan\Downloads\_Github Testing\Autobackuper\Backups\Mids Reborn\Config.json-AB_B2.zip
2020-06-12 3:52:23 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed

2020-06-12 3:53:08 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed
2020-06-12 3:53:08 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json is locked, retrying
2020-06-12 3:53:08 PM Successfully saved to C:\Users\bwfan\Downloads\_Github Testing\Autobackuper\Backups\Mids Reborn\Config.json-AB_B3.zip
2020-06-12 3:53:08 PM C:\Games\City of Heroes\Mids Reborn\Data\Config.json - Changed
```

Seems to be going smoothly with this version as well. Autobackuper recognized the file was locked in some capacity, and completed the backup when the file was freed. The backup versions are the ones expected, and overwriting old backups went as planned as well.

**Comment by Forevener** [comment] 2020-06-13 04:25
Ah, such robustness!
Before I close this issue - are these logs from three different sessions, or is it a single one?

**Comment by FelesNoctis** [comment] 2020-06-13 20:30
A single log, just spaced out by source program cycle so it's easier to read. :P

**Comment by Forevener** [comment] 2020-06-15 09:17
Why was I asking - due to the empty lines it looks like the program skips two backups for 3:52:02 PM and 3:52:23 PM.

**Comment by FelesNoctis** [comment] 2020-06-16 03:49
If you're referring to the repeated lines for the "Changed" file, nope, that's what it printed. There seems to be one "Changed" line before and after every backup cycle.

**Comment by Forevener** [comment] 2020-06-16 04:22
OK, cool, it's working as intended then!

**Closed as completed by Forevener** 2020-06-16 04:22 UTC
Labels: bug, fixed
